flags:
packages:
- '.'
# For tests
- ../glfw-pal
- ../gl-pal
extra-deps:
- inline-c-0.5.4.3
- inline-c-cpp-0.1.0.0
# For tests
- GLFW-b-1.4.7.2
- bindings-GLFW-3.1.1.3
resolver: nightly-2015-08-07
arch: x86_64
