flags:
packages:
- '.'
# For tests
- ../Thop/modules/glfw-pal
- ../Thop/modules/gl-pal
extra-deps:
- inline-c-0.5.3.4
- inline-c-cpp-0.1.0.0
# For tests
- halive-0.1.0.5
- Win32-notify-0.3.0.1
- GLFW-b-1.4.7.2
- bindings-GLFW-3.1.1.3
resolver: nightly-2015-07-22
arch: x86_64