flags:
packages:
- '.'
# For tests
- ../glfw-pal
- ../vr-pal
- ../gl-pal
- ../hydra-hs
- ../linear-extra
- ../lens-extra
- ../halive
- ../openvr-hs
- ../bindings-GLFW-3.1.1.4
resolver: nightly-2015-11-03
